global:
  resolve_timeout: 5m

route:
  receiver: 'webhook-receiver'
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 30s

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: "https://webhook.site/1acd42e1-9873-4394-be5b-c71fccbbd4c9"
        send_resolved: false