---

- name: Provision S3 Bucket
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yaml

  tasks:
    - name: Create bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        state: present
        region: "{{ region }}"
        versioning: true
        public_access:
          block_public_acls: true
          block_public_policy: true
          ignore_public_acls: true
          restrict_public_buckets: true
        tags:
          Creator: berkayalan
      register: s3_result # output

    - name: Display bucket creation output
      ansible.builtin.debug:
        var: s3_result