[debian_family]
ubuntu-node ansible_host=127.0.0.1 ansible_port=2221 ansible_user=berkay
debian-node ansible_host=127.0.0.1 ansible_port=2222 ansible_user=berkay

[redhat_family]
rocky-node ansible_host=127.0.0.1 ansible_port=2223 ansible_user=berkay

[k8s_nodes:children]
debian_family
redhat_family

[all:vars]
ansible_password=berkayalan123
ansible_sudo_pass=berkayalan123
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no'